name: "The ChRIS Project"
title: website
baseurl: '/jekyll-asciidoc-quickstart/'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
description: The Jekyll AsciiDoc Quickstart project is a leg-up in starting your own website hosted on GitHub with content based in AsciiDoc.
exclude:
  - vendor
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
